-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 23:06:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- Ravi Sadariya
-- 8895100

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dataBlizzards_Pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dataBlizzards_Pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataBlizzards_Pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `dataBlizzards_Pharmacy` ;

-- -----------------------------------------------------
-- Table `dataBlizzards_Pharmacy`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataBlizzards_Pharmacy`.`Products` ;

CREATE TABLE IF NOT EXISTS `dataBlizzards_Pharmacy`.`Products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `manufacturer` VARCHAR(45) NULL,
  `dosage_form` VARCHAR(45) NULL,
  `unit_price` VARCHAR(45) NULL,
  `stock_quantity` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataBlizzards_Pharmacy`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataBlizzards_Pharmacy`.`Customers` ;

CREATE TABLE IF NOT EXISTS `dataBlizzards_Pharmacy`.`Customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataBlizzards_Pharmacy`.`Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataBlizzards_Pharmacy`.`Invoices` ;

CREATE TABLE IF NOT EXISTS `dataBlizzards_Pharmacy`.`Invoices` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_date` VARCHAR(45) NULL,
  `total_amount` VARCHAR(45) NULL,
  `Products_product_id` INT NOT NULL,
  `Customers_customer_id` INT NOT NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `fk_Invoices_Products_idx` (`Products_product_id` ASC) ,
  INDEX `fk_Invoices_Customers1_idx` (`Customers_customer_id` ASC) ,
  CONSTRAINT `fk_Invoices_Products`
    FOREIGN KEY (`Products_product_id`)
    REFERENCES `dataBlizzards_Pharmacy`.`Products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Customers1`
    FOREIGN KEY (`Customers_customer_id`)
    REFERENCES `dataBlizzards_Pharmacy`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataBlizzards_Pharmacy`.`Invoice_Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataBlizzards_Pharmacy`.`Invoice_Items` ;

CREATE TABLE IF NOT EXISTS `dataBlizzards_Pharmacy`.`Invoice_Items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` VARCHAR(45) NULL,
  `unit_price` VARCHAR(45) NULL,
  `total_price` VARCHAR(45) NULL,
  `Invoices_invoice_id` INT NOT NULL,
  `Customers_customer_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_Invoice_Items_Invoices1_idx` (`Invoices_invoice_id` ASC) ,
  INDEX `fk_Invoice_Items_Customers1_idx` (`Customers_customer_id` ASC) ,
  CONSTRAINT `fk_Invoice_Items_Invoices1`
    FOREIGN KEY (`Invoices_invoice_id`)
    REFERENCES `dataBlizzards_Pharmacy`.`Invoices` (`invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoice_Items_Customers1`
    FOREIGN KEY (`Customers_customer_id`)
    REFERENCES `dataBlizzards_Pharmacy`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataBlizzards_Pharmacy`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dataBlizzards_Pharmacy`.`Address` ;

CREATE TABLE IF NOT EXISTS `dataBlizzards_Pharmacy`.`Address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `zip_code` VARCHAR(45) NULL,
  `Customers_customer_id` INT NOT NULL,
  PRIMARY KEY (`address_id`),
  INDEX `fk_Address_Customers1_idx` (`Customers_customer_id` ASC) ,
  CONSTRAINT `fk_Address_Customers1`
    FOREIGN KEY (`Customers_customer_id`)
    REFERENCES `dataBlizzards_Pharmacy`.`Customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `dataBlizzards_Pharmacy`.`Products` (`name`, `manufacturer`, `dosage_form`, `unit_price`, `stock_quantity`)
VALUES
  ('Medicine A', 'Manufacturer A', 'Tablet', '10.99', '50'),
  ('Medicine B', 'Manufacturer B', 'Capsule', '15.50', '30'),
  ('Medicine C', 'Manufacturer A', 'Liquid', '20.75', '20'),
  ('Medicine D', 'Manufacturer C', 'Tablet', '8.99', '45'),
  ('Medicine E', 'Manufacturer B', 'Capsule', '12.25', '40'),
  ('Medicine F', 'Manufacturer C', 'Liquid', '18.50', '25');


INSERT INTO `dataBlizzards_Pharmacy`.`Customers` (`name`, `phone_number`, `email`)
VALUES
  ('John Doe', '123-456-7890', 'john.doe@example.com'),
  ('Jane Smith', '987-654-3210', 'jane.smith@example.com'),
  ('Bob Johnson', '555-123-4567', 'bob.johnson@example.com'),
  ('Alice Brown', '777-888-9999', 'alice.brown@example.com'),
  ('Charlie White', '333-444-5555', 'charlie.white@example.com'),
  ('Eva Black', '666-777-8888', 'eva.black@example.com');


INSERT INTO `dataBlizzards_Pharmacy`.`Invoices` (`invoice_date`, `total_amount`, `Products_product_id`, `Customers_customer_id`)
VALUES
  ('2023-12-15', '50.45', 1, 1),
  ('2023-12-16', '30.75', 2, 2),
  ('2023-12-17', '25.99', 3, 3),
  ('2023-12-18', '40.50', 4, 4),
  ('2023-12-19', '35.25', 5, 5),
  ('2023-12-20', '28.99', 6, 6);


INSERT INTO `dataBlizzards_Pharmacy`.`Invoice_Items` (`quantity`, `unit_price`, `total_price`, `Invoices_invoice_id`, `Customers_customer_id`)
VALUES
  ('2', '10.99', '21.98', 1, 1),
  ('3', '15.50', '46.50', 2, 2),
  ('1', '20.75', '20.75', 3, 3),
  ('4', '8.99', '35.96', 4, 4),
  ('2', '12.25', '24.50', 5, 5),
  ('3', '18.50', '55.50', 6, 6);
  
INSERT INTO `dataBlizzards_Pharmacy`.`Address` (`street`, `city`, `zip_code`, `Customers_customer_id`)
VALUES
  ('123 Main St', 'Cityville', '12345', 1),
  ('456 Elm St', 'Townburg', '67890', 2),
  ('789 Oak St', 'Villagetown', '54321', 3),
  ('101 Pine St', 'Hamletville', '98765', 4),
  ('202 Maple St', 'Boroughburg', '24680', 5);



  
